// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjAfWZk1dm0bECFH7Bfru4PNYu9yCum24',
    appId: '1:831805889319:web:3315f402a4afea92382702',
    messagingSenderId: '831805889319',
    projectId: 'testing-dce90',
    authDomain: 'testing-dce90.firebaseapp.com',
    storageBucket: 'testing-dce90.appspot.com',
    measurementId: 'G-1413KJMQM9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxUo0hBq4I_NmmLnv859mcfmxZ0Bfzn4I',
    appId: '1:831805889319:android:693cddfcdc47b3cf382702',
    messagingSenderId: '831805889319',
    projectId: 'testing-dce90',
    storageBucket: 'testing-dce90.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVASusj-Nk735vNUGS7LNDYHSut2BVP2w',
    appId: '1:831805889319:ios:164639105af6a8d4382702',
    messagingSenderId: '831805889319',
    projectId: 'testing-dce90',
    storageBucket: 'testing-dce90.appspot.com',
    iosBundleId: 'com.example.untitledtaskmanger',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAVASusj-Nk735vNUGS7LNDYHSut2BVP2w',
    appId: '1:831805889319:ios:120c9edf5111fd35382702',
    messagingSenderId: '831805889319',
    projectId: 'testing-dce90',
    storageBucket: 'testing-dce90.appspot.com',
    iosBundleId: 'com.example.untitledtaskmanger.RunnerTests',
  );
}
